version: '3.9'
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cookbook-network
  
  user:
    build:
      context: ../cooking-user/
      dockerfile: ../Docker/user.Dockerfile
    ports:
      - "5003:80"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - cookbook-network
    
  user-relations:
    build:
      context: ../cooking-user-relations/
      dockerfile: ../Docker/user-relation.Dockerfile
    ports:
      - "5004:80"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - cookbook-network

volumes:
  postgres_data:

networks:
  cookbook-network: